
# -------------=== pbft build ===-------------
FROM ubuntu:xenial as pbft-builder

ENV VERSION=AUTO_STRICT

RUN apt-get update \
 && apt-get install -y -q --allow-downgrades \
    build-essential \
    curl \
    libssl-dev \
    gcc \
    git \
    libzmq3-dev \
    openssl \
    pkg-config \
    python3 \
    unzip \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# For Building Protobufs
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
 && curl -OLsS https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip \
 && unzip protoc-3.5.1-linux-x86_64.zip -d protoc3 \
 && rm protoc-3.5.1-linux-x86_64.zip

ENV PATH=$PATH:/protoc3/bin
RUN /root/.cargo/bin/cargo install cargo-deb

COPY . /project/sawtooth-pbft

WORKDIR /project/sawtooth-pbft

RUN export VERSION=$(./bin/get_version) \
 && sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${VERSION}\"/" Cargo.toml \
 && /root/.cargo/bin/cargo deb --deb-version $VERSION

# -------------=== pbft docker build ===-------------
FROM ubuntu:xenial

COPY --from=pbft-builder /project/sawtooth-pbft/target/debian/sawtooth*.deb /tmp

RUN apt-get update \
 && dpkg -i /tmp/sawtooth*.deb || true \
 && apt-get -f -y install

CMD pbft-engine
